### ISSUE TITLE
Out of memory on GPU Titan X

### ISSUE THREAD

**Issue by tyshiwo** [yunjey/StarGAN#8]
Hi,

I set batch_size=3, and tried the code on GPU Titan X. The memory cost keeps on increasing, and soon causes out of memory. Must I use a GPU with 24 GB memory? Any suggestions are appreciated.

Thanks!

**Comment by mrlzla** [comment]
That is pretty strange because I trained the model on CelebA dataset and use batch size equals to 48

**Comment by tyshiwo** [comment]
@mrlzla Do you also use Titan X? I haven't changed anything to the code.

**Comment by mrlzla** [comment]
Nvidia 1080ti

**Comment by tyshiwo** [comment]
@mrlzla  I changed batch_size=48, but it still didn't work. Did you get good results?

**Comment by eeric** [comment]
Fortunately, I was successful by default parameter setting.

**Comment by tyshiwo** [comment]
@mrlzla @eeric The reason is my pytorch is not completely installed, after I installed cffi/magma/cuda80, the problem is solved. Thanks!
